# Generated by Django 4.0 on 2022-01-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
        ('projects', '0002_alter_project_is_active_alter_todo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(default='Пользователь удалён', on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
    ]
